environment: default
debug: false
twig.options.cache: false

form.file: registration-form.txt

admin.username: null
admin.password: null

db.google.courses.key: null
db.google.courses.gid: null

db.google.coursesPlan.key: null
db.google.coursesPlan.gid: null

db.google.partners.key: null
db.google.partners.gid: null

db.google.studentsCompanies.key: null
db.google.studentsCompanies.gid: null

db.google.pages.key: null
db.google.pages.gid: null
