version: '2.10-updated-teachers-view-on-landing-for-mobile--'

environment: default
debug: false
twig.options.cache: false

cache.enabled: true

admin.username: null
admin.password: null

db.google.config.key: null
db.google.config.gid: null
