version: '0.16-refactoring-and-added-web-ui-course'

environment: default
debug: false
twig.options.cache: false

cache.enabled: true

admin.username: null
admin.password: null

db.google.config.key: null
db.google.config.gid: null