version: '2.97-afdb245-updatedcontacts'

environment: default
debug: false
twig.options.cache: false

cache.enabled: true

admin.username: null
admin.password: null

db.google.config.key: null
db.google.config.gid: null